test:
  fn_X: "X_local.csv"
  fn_y: "y_local.csv"
  nfolds: 5
  nrounds: 100
  early_stop_rounds: 10
  params:
    learning_rate: 0.05
    num_leaves: 31
    objective: 'binary'
    metric: 'auc'
    # min_data_in_leaf:


# num_leaves
31leaves:
  fn_X: "X_half_train_challenge_owkin.npy"
  fn_y: "Y_half_train_challenge_owkin.npy"
  nfolds: 5
  nrounds: 5000
  early_stop_rounds: 100
  params:
    learning_rate: 0.05
    num_leaves: 31
    objective: 'binary'
    metric: 'auc'
    num_threads: 30

70leaves:
  fn_X: "X_half_train_challenge_owkin.npy"
  fn_y: "Y_half_train_challenge_owkin.npy"
  nfolds: 5
  nrounds: 5000
  early_stop_rounds: 100
  params:
    learning_rate: 0.05
    num_leaves: 70
    objective: 'binary'
    metric: 'auc'
    num_threads: 30


120leaves:
  fn_X: "X_half_train_challenge_owkin.npy"
  fn_y: "Y_half_train_challenge_owkin.npy"
  nfolds: 5
  nrounds: 5000
  early_stop_rounds: 100
  params:
    learning_rate: 0.05
    num_leaves: 120
    objective: 'binary'
    metric: 'auc'
    num_threads: 30

# learning_rate
# early_stop_rounds
