test:
  type_data: "local"
  nfolds: 5
  nrounds: 100
  early_stop_rounds: 10
  params:
    learning_rate: 0.05
    num_leaves: 31
    objective: 'binary'
    metric: 'auc'
    # min_data_in_leaf:

31leaves:
  type_data: "18k"
  nfolds: 5
  nrounds: 100
  early_stop_rounds: 10
  params:
    learning_rate: 0.05
    num_leaves: 31
    objective: 'binary'
    metric: 'auc'
    num_threads: 30
    # min_data_in_leaf:
