test:
  fn_X: "X_local.csv"
  fn_y: "y_local.csv"
  nrounds: 100
  early_stop_rounds: 10
  nfolds: 5
  params:
    seed: 777
    ntrees: 100
    max_depth: 6  
    objective: 'binary:logistic'
    eval_metric: 'auc'
    nthread: 3
    subsample: 1
    colsample_bytree: 1
    min_child_weight: 1